language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
dist: bionic
cache: cargo

addons:
  apt:
    update: true
    packages:
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-ttf-2.0-0
      - libsdl2-gfx-1.0-0
  homebrew:
    update: true
    packages:
      - sdl2
      - sdl2-mixer
      - sdl2-image
      - sdl2-ttf
      - sdl2-gfx

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
