language: rust

rust:
  - stable
  - beta
  - nightly
cache: cargo

os:
  - linux
  - osx

install: true
addons:
  apt:
    packages:
      - libsdl2
      - libsdl2-mixer
      - libsdl2-image
      - libsdl2-ttf
      - libsdl2-gfx
  homebrew:
    packages:
      - sdl2
      - sdl2-mixer
      - sdl2-image
      - sdl2-ttf
      - sdl2-gfx

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
