[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["game-development", "game-engines", "graphics", "gui", "rendering"]
description = "A cross-platform graphics/UI engine framework for simple games, visualizations, and graphics demos."
documentation = "https://docs.rs/pix-engine"
edition = "2021"
keywords = ["game-engine", "graphics", "ui", "gui", "rendering"]
license = "MIT OR Apache-2.0"
name = "pix-engine"
repository = "https://github.com/lukexor/pix-engine.git"
resolver = "2"
version = "0.5.0"
exclude = ["/images"]

[package.metadata]
msrv = "1.56.1"

[package.metadata.docs.rs]
features = ["serde"]
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
num-traits = "0.2.14"
png = "0.17.1"
serde = { version = "1.0.126", features = ["derive"], optional = true }
rand = "0.8.4"
lru = "0.7.0"
rayon = "1.5.1"
anyhow = "1.0.49"
thiserror = "1.0.29"
log = "0.4.14"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["prepush-hook", "run-cargo-test", "run-cargo-clippy"]

[features]
default = []
opengl = []
# TODO: `backtrace` feature can be removed when `Backtrace` lands in stable
backtrace = ["anyhow/backtrace"]
use-vcpkg = ["sdl2/static-link", "sdl2/use-vcpkg"]

[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
sdl2 = { version = "0.35.0", default_features = false, features = ["gfx", "image", "mixer", "ttf", "unsafe_textures"] }

[target."cfg(target_arch = \"wasm32\")".dependencies]
getrandom = { version = "0.2.3", features = ["js"] }

[target."cfg(target_arch = \"wasm32\")".dev-dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen-test = "0.3.24"

[profile.dev]
opt-level = 2

[profile.release]
codegen-units = 1
lto = true

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-image[libjpeg-turbo,tiff,libwebp]", "sdl2-ttf", "sdl2-gfx", "sdl2-mixer"]
git = "https://github.com/microsoft/vcpkg"
rev = "2a31089e777fc187f1cc05338250b8e1810cfb52"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
