[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["game-development", "game-engines", "graphics", "gui", "multimedia", "rendering", "web-assembly"]
description = "A cross-platform graphics/UI engine framework for simple games, visualizations, and graphics demos."
documentation = "https://github.com/lukexor/pix-engine#readme"
edition = "2018"
homepage = "https://github.com/lukexor/pix-engine"
keywords = ["game-engine", "graphics", "ui", "gui", "rendering", "web-assembly", "sdl"]
license = "MIT/Apache-2.0"
name = "pix-engine"
readme = "README.md"
repository = "https://github.com/lukexor/pix-engine.git"
resolver = "2"
version = "0.4.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
num-traits = "0.2.14"
png = "0.16.8"
rand = "0.8.4"
serde = { version = "1.0.126", features = ["derive"], optional = true }

[features]
default = []
opengl = []

[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
include_dir = "0.6.1"
sdl2 = { version = "0.34.5", default_features = false, features = ["gfx", "image", "mixer", "ttf", "unsafe_textures"] }

[target."cfg(target_arch = \"wasm32\")".dependencies]
getrandom = { version = "0.2.3", features = ["js"] }

[target."cfg(target_arch = \"wasm32\")".dev-dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen-test = "0.3.24"

[profile.dev]
opt-level = 2

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true

[profile.test]
opt-level = 2

