[package]
name = "pix-engine"
version = "0.4.0"
license = "MIT/Apache-2.0"
description = "A simple, cross-platform graphics/UI engine framework with a minimal interface."
categories = ["graphics", "gui", "multimedia", "rendering"]
keywords = ["graphics", "ui", "gui", "rendering"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/pix-engine"
repository = "https://github.com/lukexor/pix-engine.git"
homepage = "https://github.com/lukexor/pix-engine"
edition = "2018"

[dependencies]
rand = "0.7"
sdl2 = { version = "0.34", features = ["gfx", "image", "mixer", "ttf"] }
