[package]
name = "pix-engine"
version = "0.4.0"
license = "MIT/Apache-2.0"
description = "A cross-platform graphics/UI engine framework for simple games, visualizations, and graphics demos."
categories = ["game-development", "game-engines", "graphics", "gui", "multimedia", "rendering", "web-assembly"]
keywords = ["game-engine", "graphics", "ui", "gui", "rendering", "web-assembly", "sdl"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/pix-engine"
repository = "https://github.com/lukexor/pix-engine.git"
homepage = "https://github.com/lukexor/pix-engine"
edition = "2018"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
include_dir = "^0.6"
num-traits = "^0.2"
png = "^0.16"
rand = "^0.8"
getrandom = { version = "^0.2", features=["js"] }
rng = "^0.1"
bitflags = "^1.2"
lazy_static = "^1.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.sdl2]
version = "^0.34"
default_features = false
features = ["gfx", "image", "mixer", "ttf", "unsafe_textures"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0.2"
js-sys = "^0.3"
web-sys = "^0.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_error_panic_hook = "^0.1"
wasm-bindgen-test = "^0.3"


[profile.dev]
opt-level = 2
split-debuginfo = "unpacked"

[profile.release]
lto = true
codegen-units = 1
