[package]
name = "pix-engine"
version = "0.5.0"
license = "MIT/Apache-2.0"
description = "A simple, cross-platform graphics/UI engine framework with a minimal interface."
categories = ["graphics", "gui", "multimedia", "rendering"]
keywords = ["graphics", "ui", "gui", "rendering"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/pix-engine"
repository = "https://github.com/lukexor/pix-engine.git"
homepage = "https://github.com/lukexor/pix-engine"
edition = "2018"

[dependencies]
approx = "0.4"
include_dir = "0.6"
num-traits = "0.2"
png = "0.16"
rand = "0.8"
rng = "0.1"

[dependencies.sdl2]
version = "0.34"
default_features = false
features = ["gfx", "image", "mixer", "ttf", "unsafe_textures"]

[profile.release]
lto = true
codegen-units = 1
