[package]
name = "pix-engine"
version = "0.4.0"
license = "MIT/Apache-2.0"
description = "A cross-platform graphics/UI engine framework for simple games, visualizations, and graphics demos."
categories = [
  "game-development",
  "game-engines",
  "graphics",
  "gui",
  "multimedia",
  "rendering",
  "web-assembly",
]
keywords = ["game-engine", "graphics", "ui", "gui", "rendering", "web-assembly", "sdl"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/pix-engine#readme"
repository = "https://github.com/lukexor/pix-engine.git"
homepage = "https://github.com/lukexor/pix-engine"
edition = "2018"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
num-traits = "0.2.14"
png = "0.16.8"
rand = "0.8.4"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.126"

[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
include_dir = "0.6.1"

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.sdl2]
default_features = false
features = ["gfx", "image", "mixer", "ttf", "unsafe_textures"]
version = "0.34.5"

[target."cfg(target_arch = \"wasm32\")".dependencies.getrandom]
features = ["js"]
version = "0.2.3"

[target."cfg(target_arch = \"wasm32\")".dev-dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen-test = "0.3.24"

[profile.dev]
split-debuginfo = "unpacked"

[profile.dev.package.sdl2]
opt-level = 2

[profile.test.package.sdl2]
opt-level = 2

[profile.release]
codegen-units = 1
lto = true
