name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            env:
              LIBRARY_PATH: "/usr/local/lib"
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/vcpkg/
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/debug/
          target/doc/
          target/vcpkg/
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}

    - name: Install cargo-vcpkg
      run: cargo install cargo-vcpkg --force

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: cargo vcpkg -v build

    - name: Build source
      run: cargo build --all-targets --features "serde use-vcpkg" --verbose

    - name: Build docs
      run: cargo doc --features "serde use-vcpkg" --verbose

    - name: Run unit tests
      run: cargo test --features "serde use-vcpkg" --verbose

    - name: Run integration tests
      run: |
        # Skip until linux is set up with a video device and windows with an
        # audio device
        # cargo test run_engine -- --test-threads=1 --ignored
