name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created, edited]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  [macos-latest, ubuntu-latest, windows-latest]
        # MSRV 1.55
        toolchain: [nightly, beta, stable, 1.55]
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1

    - name: Install cargo-vcpkg
      run: cargo install cargo-vcpkg

    - name: Install dependencies
      run: cargo vcpkg -v build

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Check lints
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: Build source
      run: cargo build --all-targets --features "serde use-vcpkg" --verbose

    - name: Build docs
      run: cargo doc --features "serde use-vcpkg" --verbose

    - name: Run unit tests
      run: cargo test --features "serde use-vcpkg" --verbose

    - name: Run integration tests
      # TODO: Fix missing video device on linux and audio API issue on windows
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        cargo test run_engine --features "serde use-vcpkg" -- --test-threads=1 --ignored
