name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created, edited]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  [macos-latest, ubuntu-latest, windows-latest]
        # MSRV 1.55
        toolchain: [nightly, beta, stable, 1.55]
        include:
          - os: macos-latest
            build_cache: |
              ~/.cache/vcpkg/archives
          - os: ubuntu-latest
            build_cache: |
              ~/.cache/vcpkg/archives
          - os: windows-latest
            build_cache: |
              %LocalAppData%\vcpkg\archives
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v1

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: Install build dependencies
      run: cargo install cargo-vcpkg

    - name: Cache build dependencies
      id: cache-build
      uses: actions/cache@v2
      with:
        path: ${{ matrix.build_cache }}
        key: ${{ matrix.os }}-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ matrix.os }}-

    - name: Build dependencies
      run: cargo vcpkg -v build

    - name: Build source
      run: cargo build --all-targets --features "serde use-vcpkg" --verbose

    - name: Build documentation
      run: cargo doc --features "serde use-vcpkg" --verbose

    - name: Run unit tests
      run: cargo test --features "serde use-vcpkg" --verbose

    - name: Run integration tests
      # TODO: Fix missing video device on linux and audio API issue on windows
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        cargo test run_engine --features "serde use-vcpkg" -- --test-threads=1 --ignored
