---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, 1.67.0]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: ./.github/actions/install-linuxbrew
        if: matrix.os == 'ubuntu-latest'
      - uses: ./.github/actions/install-sdl2
        if: matrix.os != 'windows-latest'
      - name: Build
        shell: bash
        run: |
          cargo build --all-targets --features "serde" --verbose
          # TODO: Enable when WASM development begins
          # bin/build_wasm.sh --dev
      - run: cargo doc --features "serde" --verbose
      - run: cargo test --features "serde" --verbose
      # TODO: Fix missing video device on linux and audio API issue on windows
      - if: matrix.os == 'macos-latest'
        # yamllint disable-line rule:line-length
        run: cargo test run_engine --features "serde" -- --test-threads=1 --ignored
