name: Coverage

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
    - name: Cache Linuxbrew
      uses: actions/cache@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/Homebrew
          /home/linuxbrew/.linuxbrew/
        key: ${{ runner.os }}-linuxbrew-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Linuxbrew
      if: matrix.os == 'ubuntu-latest'
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
        test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        set -xeuo pipefail
        echo "LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install build-essential
    - name: Code Coverage
      run: |
        cargo +nightly tarpaulin --verbose --features serde --timeout 120 --run-types Tests,Doctests
    - name: Upload Coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
