name: Cargo Package

on:
  release:
    types: [created]

jobs:
  package:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Publish Crate
      uses: katyo/publish-crates@v1
        with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
