---
name: Cargo Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: ./.github/workflows/install_sdl2
        with:
          os: macos-latest
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
